[workspace]
members = ["types", "color_sensor", "controller", "dobot", "presence_sensor"]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.85"
version = "0.1.0"

[workspace.dependencies]
dust_dds = { git = "https://github.com/s2e-systems/dust-dds", branch = "poll_ready_tasks" }

