module robot_arm_case {

    enum Presence {
        Present,
        NotPresent
    };

    enum Color {
        Red,
        Blue,
        Green,
        Undefined
    };

    enum Suction {
        On,
        Off
    };

    struct ConveyorBeltSpeed {
        long speed;
    };

    enum MoveType {
        moveJ,
        moveL,
        jump
    };

    struct RobotPose {
        float x;
        float y;
        float z;
        float r;
    };

    enum SensorState {
        Available,
        NotAvailable
    };
};