[package]
name = "presence_sensor"
version = "0.1.0"
edition = "2021"
build = "../build.rs"

[dependencies]
dust_dds = "0.7"
rust_gpiozero = "0.2"

[build-dependencies]
dust_dds_gen = { version = "0.7" }
